version: '3.8'

services:
  ebalert-bot:
    build: .
    container_name: ebalert-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
      - LOGGING=INFO
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 